name: Java CI

on:
  push:
    branches:
      - main
      - 'fix-*'  # This pattern will trigger on branches that start with "fix-"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'adoptium'

    # Step 3: Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Build and run tests
    - name: Build with Maven
      run: mvn -B clean install

    # Step 5: Run tests
    - name: Run tests
      run: mvn test

    # Optional Step 6: Code Coverage (if you use a coverage tool)
    - name: Upload Code Coverage Report
      if: success() && steps.build.outputs.coverage-report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/site/jacoco/index.html
