name: Java CI

on:
  push:
    branches:
      - main
      - 'fix-*'  # This pattern will trigger on branches that start with "fix-"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'

    # Build and run tests
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Run tests
    - name: Run tests
      run: mvn test

